[package]
name = "cetkaik_compact_representation"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.1"
cetkaik_core = "0.4.0"
